# Generated by Django 5.2.8 on 2025-11-08 15:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_analysis_model', models.CharField(default='command-r7b', help_text='Cohere model used when analysing job postings.', max_length=120)),
                ('job_temperature', models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Sampling temperature for job analysis requests.', max_digits=3)),
                ('job_additional_prompt', models.TextField(blank=True, help_text='Optional extra instructions appended to job analysis prompts.')),
                ('resume_analysis_model', models.CharField(default='command-r7b', help_text='Cohere model used when analysing resumes.', max_length=120)),
                ('resume_temperature', models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Sampling temperature for resume analysis requests.', max_digits=3)),
                ('resume_additional_prompt', models.TextField(blank=True, help_text='Optional extra instructions appended to resume analysis prompts.')),
                ('auto_analyze_resumes', models.BooleanField(default=True, help_text='Automatically trigger AI analysis after uploading a resume.')),
                ('enable_pdf_extraction', models.BooleanField(default=True, help_text='Allow automatic text extraction from PDF resumes.')),
                ('enable_docx_extraction', models.BooleanField(default=True, help_text='Allow automatic text extraction from DOCX resumes.')),
                ('enable_text_extraction', models.BooleanField(default=True, help_text='Allow automatic text extraction from plain text resumes.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI setting',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
