# Generated by Django 5.2.8 on 2025-11-08 12:08

import applications.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('resume_file', models.FileField(upload_to=applications.models.resume_upload_path)),
                ('resume_text', models.TextField(blank=True, help_text='Plain text extracted from the uploaded resume.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ('-created_at',),
            },
        ),
    ]
