# Generated by Django 5.2.8 on 2025-11-08 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('jobs', '0003_jobposition_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the resume.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['uploaded_by'], name='application_uploade_af379e_idx'),
        ),
    ]
