# Generated by Django 5.2.8 on 2025-11-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_update_application_statuses'),
        ('applications', '0003_application_uploaded_by_and_more'),
    ]

    operations = [
    ]
