# Generated by Django 5.2.8 on 2025-11-08 12:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Public title of the job.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description used for AI matching.')),
                ('department', models.CharField(blank=True, help_text='Optional department or team for reporting.', max_length=120)),
            ],
            options={
                'verbose_name': 'job position',
                'verbose_name_plural': 'job positions',
                'ordering': ('-created_at',),
            },
        ),
    ]
