# Generated by Django 5.2.8 on 2025-11-08 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the job posting.', on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['department'], name='jobs_jobpos_departm_90ccdd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['created_at'], name='jobs_jobpos_created_f0e7a1_idx'),
        ),
    ]
