# Generated by Django 5.2.8 on 2025-11-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source URL if this job was imported from an external site.'),
        ),
    ]
