from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from core.models import TimeStampedModel, UUIDModel


class ResumeAnalysis(UUIDModel, TimeStampedModel):
    """
    Stores the output of the AI resume analysis for a single application.

    The `analyzed_at` timestamp is kept separate from the inherited
    `updated_at` so that we can record when the AI actually processed the
    resume, regardless of any later edits (e.g. manual overrides).
    """

    application = models.OneToOneField(
        "applications.Application",
        related_name="analysis",
        on_delete=models.CASCADE,
        help_text=_("Application that was analyzed."),
    )
    match_score = models.DecimalField(
        max_digits=5,
        decimal_places=4,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(1)],
        help_text=_("Cohere-determined match score between 0 and 1."),
    )
    summary = models.TextField(
        blank=True,
        help_text=_("Concise summary of the candidate generated by Cohere."),
    )
    improvements = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Structured suggestions for improving the candidate's fit."),
    )
    cohere_model = models.CharField(
        max_length=120,
        blank=True,
        help_text=_("Name of the Cohere model used for the analysis."),
    )
    analyzed_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        ordering = ("-analyzed_at",)
        verbose_name = _("resume analysis")
        verbose_name_plural = _("resume analyses")
        indexes = [
            models.Index(fields=("match_score",)),
            models.Index(fields=("analyzed_at",)),
        ]

    def __str__(self) -> str:
        return f"Analysis for {self.application.full_name} ({self.match_score:.2%})"
