# Generated by Django 5.2.8 on 2025-11-08 12:08

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=4, default=0, help_text='Cohere-determined match score between 0 and 1.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('summary', models.TextField(blank=True, help_text='Concise summary of the candidate generated by Cohere.')),
                ('improvements', models.JSONField(blank=True, default=dict, help_text="Structured suggestions for improving the candidate's fit.")),
                ('cohere_model', models.CharField(blank=True, help_text='Name of the Cohere model used for the analysis.', max_length=120)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'resume analysis',
                'verbose_name_plural': 'resume analyses',
                'ordering': ('-analyzed_at',),
            },
        ),
    ]
