# Generated by Django 5.2.8 on 2025-11-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzer', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='application',
            field=models.OneToOneField(help_text='Application that was analyzed.', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='applications.application'),
        ),
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['match_score'], name='analyzer_re_match_s_ad5b77_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['analyzed_at'], name='analyzer_re_analyze_6d8e81_idx'),
        ),
    ]
